#!/usr/bin/env bash

set -x

declare -A color

#color["focused"]="0xE0808080"
#color["normal"]="0x00010101"
#color["preselect"]="0xE02d74da"

# See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config layout                      bsp

yabai -m config top_padding                 4
yabai -m config bottom_padding              4
yabai -m config left_padding                4
yabai -m config right_padding               4
yabai -m config window_gap                  4

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off

yabai -m config window_topmost              off
yabai -m config window_opacity              off
yabai -m config window_shadow               float

yabai -m config window_border               on
yabai -m config window_border_width         2
#yabai -m config active_window_border_color  "${color["focused"]}"
#yabai -m config normal_window_border_color  "${color["normal"]}"
#yabai -m config insert_feedback_color       "${color["preselect"]}"

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.90
yabai -m config split_ratio                 0.50

yabai -m config auto_balance                off

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

set +x
