---
  - name: bootstrap
    hosts: localhost
    tasks:
      - name: install packages
        ansible.builtin.dnf: 
          name: 
            - zsh
            - git
            - neovim
            - go
            - rust
            - chrome
            - nodejs
          state: latest
